### PR TITLE
Create images-links.md

### PR DESCRIPTION
**Pull request by katsmamina**
Added images link by posting them into one md file

### CODE REVIEW

**Review by rayanejsilva — CHANGES_REQUESTED** [review]
@katsmamina I think it is better to download all the images and save them in the images folder, not only the links. When we start to make the website we need to have them in our computer.

**Comment by katsmamina** [comment]
I can do that, too. No prob

**Comment by rayanejsilva** [comment]
@katsmamina Can I close this PR?

**Comment by katsmamina** [comment]
yes you can close it

**Pull request closed without merging**
