### PR TITLE
added Lizhen as contact

### PR DESCRIPTION
**Pull request by katsmamina**
I just saw that the HYF website has only TWO people as team members while they actually hired Lizhen! :) P.S. We would need to add her photo, too

### CODE REVIEW

**Comment by wadiawadia** [comment]
i think she s still on team we have to added her picture

**Comment by JTLiberona** [comment]
Indeed.
That's something to consider for the media files and Contact Info. ;)

**Comment by wadiawadia** [comment]
great!

**Comment by rayanejsilva** [comment]
@katsmamina good catch! I asked Evan about her photo. 😊

**Pull request merged**
