### PR TITLE
added user stories for student

### PR DESCRIPTION
**Pull request by katsmamina**
first touch for the "student" perspective
also deleted the existing lines left from the previous project (loruki) and structured the content – feel free to add your part!

### CODE REVIEW

**Review by wadiawadia — COMMENTED** [review]
i wrote the part of sponsor i hope will change , because really i have difficulty to know how is works , i will try my best.

**Comment by katsmamina** [comment]
Hey Widad! We are supposed to create separate branches for each commit. Could you do it or do you need some help?

**Comment by wadiawadia** [comment]
when i wroie the part of the sponsor i have to do it in separate branche ? i didnt know , i will do it.

**Comment by katsmamina** [comment]
yes, normally it's a separate branch for each commit :) 
and then this separate branch is merged into main

**Comment by wadiawadia** [comment]
i have to write a new request just with MUST have and SHOULD have for sponsor ?

**Comment by katsmamina** [comment]
Also: it's important to give precise names to each commit so that we don't get lost later, with hundreds of small commits. 
e.g. "Update backlog.md" is not a precise name, because the changes are not specified
It's easy to change the name of the commit on GitHub, and can also be done from CLI: 
git commit -m "your comment"

**Comment by wadiawadia** [comment]
ok i will try if isn t good tomorrow advice me , thank you

**Comment by katsmamina** [comment]
hmmmm... I am afraid that if you write it again, it will create conflict with main ! Not sure what's better to do 
I would say let's leave it like this for now because there is no conflict and the file is rather simple .

however, next time it's better to create a branch for each commit

**Comment by wadiawadia** [comment]
ok i am with you

**Pull request merged**
